# Examples and Exercises from Think Stats, 2nd Edition

http://thinkstats2.com

Copyright 2016 Allen B. Downey

MIT License: https://opensource.org/licenses/MIT


In [102]:
from __future__ import print_function, division

import nsfg

import pandas as pd
from IPython.display import display

pd.set_option('display.max_columns', None)

## Examples from Chapter 1

Read NSFG data into a Pandas DataFrame.

In [103]:
preg = nsfg.ReadFemPreg()
preg.head()

caseid  pregordr  howpreg_n  howpreg_p  moscurrp  nowprgdk  pregend1  \
0       1         1        NaN        NaN       NaN       NaN       6.0   
1       1         2        NaN        NaN       NaN       NaN       6.0   
2       2         1        NaN        NaN       NaN       NaN       5.0   
3       2         2        NaN        NaN       NaN       NaN       6.0   
4       2         3        NaN        NaN       NaN       NaN       6.0   

   pregend2  nbrnaliv  multbrth  cmotpreg  prgoutcome  cmprgend  flgdkmo1  \
0       NaN       1.0       NaN       NaN         1.0    1093.0       NaN   
1       NaN       1.0       NaN       NaN         1.0    1166.0       NaN   
2       NaN       3.0       5.0       NaN         1.0    1156.0       NaN   
3       NaN       1.0       NaN       NaN         1.0    1198.0       NaN   
4       NaN       1.0       NaN       NaN         1.0    1204.0       NaN   

   cmprgbeg  ageatend  hpageend  gestasun_m  gestasun_w  wksgest  mosgest  \
0    1084.0       NaN       NaN         9.0         0.0     39.0      9.0   
1    1157.0       NaN       NaN         9.0         0.0     39.0      9.0   
2    1147.0       NaN       NaN         0.0        39.0     39.0      9.0   
3    1189.0       NaN       NaN         0.0        39.0     39.0      9.0   
4    1195.0       NaN       NaN         0.0        39.0     39.0      9.0   

   dk1gest  dk2gest  dk3gest  bpa_bdscheck1  bpa_bdscheck2  bpa_bdscheck3  \
0      NaN      NaN      NaN            0.0            NaN            NaN   
1      NaN      NaN      NaN            0.0            NaN            NaN   
2      NaN      NaN      NaN            0.0            NaN            NaN   
3      NaN      NaN      NaN            0.0            NaN            NaN   
4      NaN      NaN      NaN            0.0            NaN            NaN   

   babysex  birthwgt_lb  birthwgt_oz  lobthwgt  babysex2  birthwgt_lb2  \
0      1.0          8.0         13.0       NaN       NaN           NaN   
1      2.0          7.0         14.0       NaN       NaN           NaN   
2      1.0          9.0          2.0       NaN       2.0           2.0   
3      2.0          7.0          0.0       NaN       NaN           NaN   
4      2.0          6.0          3.0       NaN       NaN           NaN   

   birthwgt_oz2  lobthwgt2  babysex3  birthwgt_lb3  birthwgt_oz3  lobthwgt3  \
0           NaN        NaN       NaN           NaN           NaN        NaN   
1           NaN        NaN       NaN           NaN           NaN        NaN   
2           0.0        NaN       1.0           1.0           4.0        NaN   
3           NaN        NaN       NaN           NaN           NaN        NaN   
4           NaN        NaN       NaN           NaN           NaN        NaN   

   cmbabdob  kidage  hpagelb  birthplc  paybirth1  paybirth2  paybirth3  \
0    1093.0   138.0     37.0       NaN        NaN        NaN        NaN   
1    1166.0    65.0     42.0       1.0        1.0        2.0        NaN   
2    1156.0    75.0     24.0       NaN        NaN        NaN        NaN   
3    1198.0    33.0     25.0       1.0        3.0        NaN        NaN   
4    1204.0    27.0     25.0       1.0        3.0        NaN        NaN   

   knewpreg  trimestr  ltrimest  priorsmk  postsmks  npostsmk  getprena  \
0       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1       2.0       NaN       NaN       0.0       5.0       NaN       1.0   
2       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
3       3.0       NaN       NaN       0.0       5.0       NaN       1.0   
4       2.0       NaN       NaN       0.0       5.0       NaN       1.0   

   bgnprena  pnctrim  lpnctri  workpreg  workborn  didwork  matweeks  weeksdk  \
0       NaN      NaN      NaN       NaN       NaN      NaN       NaN      NaN   
1       4.0      NaN      NaN       5.0       NaN      NaN       NaN      NaN   
2       NaN      NaN      NaN       NaN       NaN      NaN       NaN      NaN   
3       4.0      

Print the column names.

In [28]:
preg.columns

Index(['caseid', 'pregordr', 'howpreg_n', 'howpreg_p', 'moscurrp', 'nowprgdk',
       'pregend1', 'pregend2', 'nbrnaliv', 'multbrth',
       ...
       'laborfor_i', 'religion_i', 'metro_i', 'basewgt', 'adj_mod_basewgt',
       'finalwgt', 'secu_p', 'sest', 'cmintvw', 'totalwgt_lb'],
      dtype='object', length=244)

Select a single column name.

In [29]:
preg.columns[1]

'pregordr'

Select a column and check what type it is.

In [30]:
pregordr = preg['pregordr']
type(pregordr)

pandas.core.series.Series

Print a column.

In [42]:
pregordr

0        1
1        2
2        1
3        2
4        3
5        1
6        2
7        3
8        1
9        2
10       1
11       1
12       2
13       3
14       1
15       2
16       3
17       1
18       2
19       1
20       2
21       1
22       2
23       1
24       2
25       3
26       1
27       1
28       2
29       3
        ..
13563    2
13564    3
13565    1
13566    1
13567    1
13568    2
13569    1
13570    2
13571    3
13572    4
13573    1
13574    2
13575    1
13576    1
13577    2
13578    1
13579    2
13580    1
13581    2
13582    3
13583    1
13584    2
13585    1
13586    2
13587    3
13588    1
13589    2
13590    3
13591    4
13592    5
Name: pregordr, Length: 13593, dtype: int64

Select a single element from a column.

In [32]:
pregordr[0]

1

Select a slice from a column.

In [33]:
pregordr[2:5]


2    1
3    2
4    3
Name: pregordr, dtype: int64

Select a column using dot notation.

In [34]:
pregordr = preg.pregordr

Count the number of times each value occurs.

In [35]:
preg.outcome.value_counts().sort_index()

1    9148
2    1862
3     120
4    1921
5     190
6     352
Name: outcome, dtype: int64

Check the values of another variable.

In [36]:
preg.birthwgt_lb.value_counts().sort_index()

0.0        8
1.0       40
2.0       53
3.0       98
4.0      229
5.0      697
6.0     2223
7.0     3049
8.0     1889
9.0      623
10.0     132
11.0      26
12.0      10
13.0       3
14.0       3
15.0       1
Name: birthwgt_lb, dtype: int64

Make a dictionary that maps from each respondent's `caseid` to a list of indices into the pregnancy `DataFrame`.  Use it to select the pregnancy outcomes for a single respondent.

In [51]:
caseid = 10229
preg_map = nsfg.MakePregMap(preg)
indices = preg_map[caseid]
preg.outcome[indices].values

array([4, 4, 4, 4, 4, 4, 1], dtype=int64)

In [47]:
indices

[11093, 11094, 11095, 11096, 11097, 11098, 11099]

## Exercises

Select the `birthord` column, print the value counts, and compare to results published in the [codebook](http://www.icpsr.umich.edu/nsfg6/Controller?displayPage=labelDetails&fileCode=PREG&section=A&subSec=8016&srtLabel=611933)

In [54]:
# Solution goes here
preg['birthord'].value_counts()

1.0     4413
2.0     2874
3.0     1234
4.0      421
5.0      126
6.0       50
7.0       20
8.0        7
9.0        2
10.0       1
Name: birthord, dtype: int64

We can also use `isnull` to count the number of nans.

In [14]:
preg.birthord.isnull().sum()

4445

Select the `prglngth` column, print the value counts, and compare to results published in the [codebook](http://www.icpsr.umich.edu/nsfg6/Controller?displayPage=labelDetails&fileCode=PREG&section=A&subSec=8016&srtLabel=611931)

In [68]:
# Solution goes here
preg['prglngth'].value_counts()

39    4744
40    1120
38     609
9      594
41     591
6      543
37     457
13     446
4      412
8      409
35     357
36     329
42     328
17     253
11     202
30     198
5      181
7      175
12     170
3      151
43     148
22     147
10     137
32     122
26     117
2       78
34      60
33      50
44      46
16      44
15      39
28      38
21      37
19      34
24      31
31      29
14      29
29      23
20      18
18      17
0       15
25      15
23      12
45      10
1        9
27       8
48       7
50       2
46       1
47       1
Name: prglngth, dtype: int64

To compute the mean of a column, you can invoke the `mean` method on a Series.  For example, here is the mean birthweight in pounds:

In [16]:
preg.totalwgt_lb.mean()

7.265628457623368

Create a new column named <tt>totalwgt_kg</tt> that contains birth weight in kilograms.  Compute its mean.  Remember that when you create a new column, you have to use dictionary syntax, not dot notation.

In [69]:
# Solution goes here
preg['totalwgt_kg']=preg['totalwgt_lb']/2.2

In [70]:
preg['totalwgt_kg'].mean()

3.302558389828807

`nsfg.py` also provides `ReadFemResp`, which reads the female respondents file and returns a `DataFrame`:

In [71]:
resp = nsfg.ReadFemResp()

`DataFrame` provides a method `head` that displays the first five rows:

In [72]:
resp.head()

caseid  rscrinf  rdormres  rostscrn  rscreenhisp  rscreenrace  age_a  \
0    2298        1         5         5            1          5.0     27   
1    5012        1         5         1            5          5.0     42   
2   11586        1         5         1            5          5.0     43   
3    6794        5         5         4            1          5.0     15   
4     616        1         5         4            1          5.0     20   

   age_r  cmbirth  agescrn     ...      pubassis_i      basewgt  \
0     27      902       27     ...               0  3247.916977   
1     42      718       42     ...               0  2335.279149   
2     43      708       43     ...               0  2335.279149   
3     15     1042       15     ...               0  3783.152221   
4     20      991       20     ...               0  5341.329968   

   adj_mod_basewgt     finalwgt  secu_r  sest  cmintvw  cmlstyr  screentime  \
0      5123.759559  5556.717241       2    18     1234     1222    18:26:36   
1      2846.799490  4744.191350       2    18     1233     1221    16:30:59   
2      2846.799490  4744.191350       2    18     1234     1222    18:19:09   
3      5071.464231  5923.977368       2    18     1234     1222    15:54:43   
4      6437.335772  7229.128072       2    18     1233     1221    14:19:44   

    intvlngth  
0  110.492667  
1   64.294000  
2   75.149167  
3   28.642833  
4   69.502667  

[5 rows x 3087 columns]

Select the `age_r` column from `resp` and print the value counts.  How old are the youngest and oldest respondents?

In [76]:
# Solution goes here
resp['age_r'].value_counts().sort_index()

15    217
16    223
17    234
18    235
19    241
20    258
21    267
22    287
23    282
24    269
25    267
26    260
27    255
28    252
29    262
30    292
31    278
32    273
33    257
34    255
35    262
36    266
37    271
38    256
39    215
40    256
41    250
42    215
43    253
44    235
Name: age_r, dtype: int64

We can use the `caseid` to match up rows from `resp` and `preg`.  For example, we can select the row from `resp` for `caseid` 2298 like this:

In [79]:
resp[resp['caseid']==2298]

# or 
resp[resp.caseid==2298]

caseid  rscrinf  rdormres  rostscrn  rscreenhisp  rscreenrace  age_a  \
0    2298        1         5         5            1          5.0     27   

   age_r  cmbirth  agescrn     ...      pubassis_i      basewgt  \
0     27      902       27     ...               0  3247.916977   

   adj_mod_basewgt     finalwgt  secu_r  sest  cmintvw  cmlstyr  screentime  \
0      5123.759559  5556.717241       2    18     1234     1222    18:26:36   

    intvlngth  
0  110.492667  

[1 rows x 3087 columns]

And we can get the corresponding rows from `preg` like this:

In [22]:
preg[preg.caseid==2298]

caseid  pregordr  howpreg_n  howpreg_p  moscurrp  nowprgdk  pregend1  \
2610    2298         1        NaN        NaN       NaN       NaN       6.0   
2611    2298         2        NaN        NaN       NaN       NaN       6.0   
2612    2298         3        NaN        NaN       NaN       NaN       6.0   
2613    2298         4        NaN        NaN       NaN       NaN       6.0   

      pregend2  nbrnaliv  multbrth     ...       laborfor_i  religion_i  \
2610       NaN       1.0       NaN     ...                0           0   
2611       NaN       1.0       NaN     ...                0           0   
2612       NaN       1.0       NaN     ...                0           0   
2613       NaN       1.0       NaN     ...                0           0   

      metro_i      basewgt  adj_mod_basewgt     finalwgt  secu_p  sest  \
2610        0  3247.916977      5123.759559  5556.717241       2    18   
2611        0  3247.916977      5123.759559  5556.717241       2    18   
2612        0  3247.916977      5123.759559  5556.717241       2    18   
2613        0  3247.916977      5123.759559  5556.717241       2    18   

      cmintvw  totalwgt_lb  
2610      NaN       6.8750  
2611      NaN       5.5000  
2612      NaN       4.1875  
2613      NaN       6.8750  

[4 rows x 244 columns]

How old is the respondent with `caseid` 1?

In [94]:
# Solution goes here
resp[resp['caseid']==1]

caseid  rscrinf  rdormres  rostscrn  rscreenhisp  rscreenrace  age_a  \
1069       1        1         5         4            5          5.0     44   

      age_r  cmbirth  agescrn    ...      pubassis_i      basewgt  \
1069     44      695       44    ...               0  3410.389399   

      adj_mod_basewgt     finalwgt  secu_r  sest  cmintvw  cmlstyr  \
1069      3869.349602  6448.271112       2     9     1231     1219   

      screentime  intvlngth  
1069    19:56:43  67.563833  

[1 rows x 3087 columns]

What are the pregnancy lengths for the respondent with `caseid` 2298?

In [95]:
# Solution goes here
resp[resp['caseid']==2298].pr

caseid  rscrinf  rdormres  rostscrn  rscreenhisp  rscreenrace  age_a  \
0    2298        1         5         5            1          5.0     27   

   age_r  cmbirth  agescrn     ...      pubassis_i      basewgt  \
0     27      902       27     ...               0  3247.916977   

   adj_mod_basewgt     finalwgt  secu_r  sest  cmintvw  cmlstyr  screentime  \
0      5123.759559  5556.717241       2    18     1234     1222    18:26:36   

    intvlngth  
0  110.492667  

[1 rows x 3087 columns]

What was the birthweight of the first baby born to the respondent with `caseid` 5012?

In [96]:
# Solution goes here

In [104]:
resp[resp['caseid']==5012]

caseid  rscrinf  rdormres  rostscrn  rscreenhisp  rscreenrace  age_a  \
1    5012        1         5         1            5          5.0     42   

   age_r  cmbirth  agescrn  marstat  fmarstat  fmarit  evrmarry  hisp  \
1     42      718       42        1       NaN       1         1     5   

   hispgrp  numrace  roscnt  hplocale  manrel  fl_rage  fl_rrace  fl_rhisp  \
1      NaN        1       2       1.0     1.0        0         0         0   

   goschol  vaca  higrade  compgrd  havedip  dipged  cmhsgrad  havedeg  \
1        5   NaN       14      5.0      1.0     2.0       NaN      5.0   

   degrees  wthparnw  onown  intact  parmarr  lvsit14f  lvsit14m  womrasdu  \
1      NaN         2    5.0     1.0        1       NaN       NaN       NaN   

   momdegre  momworkd  momchild  momfstch  mom18  manrasdu  daddegre  \
1       1.0       2.0       5.0       4.0    NaN       NaN       2.0   

   bothbiol  intact18  onown18  numbabes  totplacd  nplaced  ndied  nadoptv  \
1         0         1        5         1       0.0        0      0        0   

   hasbabes  cmlastlb  cmfstprg  cmlstprg  menarche  pregnowq  maybpreg  \
1         1     991.0     991.0     991.0        12       5.0       NaN   

   numpregs  everpreg  currpreg  moscurrp  giveadpt  ngivenad  otherkid  \
1       1.0         1         5       NaN       5.0       NaN       5.0   

   nothrkid  sexothkd  relothkd  adptotkd  tryadopt  tryeithr  stilhere  \
1       NaN       NaN       NaN       NaN       NaN       NaN       NaN   

   cmokdcam  othkdfos  cmokddob  othkdspn  othkdrac1  othkdrac2  kdbstrac  \
1       NaN       NaN       NaN       NaN        NaN        NaN       NaN   

   okbornus  okdisabl1  sexothkd2  relothkd2  adptotkd2  tryadopt2  tryeithr2  \
1       NaN        NaN        NaN        NaN        NaN        NaN        NaN   

   stilhere2  cmokdcam2  othkdfos2  cmokddob2  othkdspn2  othkdrac6  \
1        NaN        NaN        NaN        NaN        NaN        NaN   

   okbornus2  okdisabl5  sexothkd3  relothkd3  adptotkd3  tryadopt3  \
1        NaN        NaN        NaN        NaN        NaN        NaN   

   tryeithr3  stilhere3  cmokdcam3  othkdfos3  cmokddob3  othkdspn3  \
1        NaN        NaN        NaN        NaN        NaN        NaN   

   othkdrac11  okbornus3  okdisabl9  sexothkd4  relothkd4  adptotkd4  \
1         NaN        NaN        NaN        NaN        NaN        NaN   

   tryadopt4  tryeithr4  stilhere4  cmokdcam4  othkdfos4  cmokddob4  \
1        NaN        NaN        NaN        NaN        NaN        NaN   

   othkdspn4  othkdrac16  okbornus4  okdisabl13  sexothkd5  relothkd5  \
1        NaN         NaN        NaN         NaN        NaN        NaN   

   adptotkd5  tryadopt5  tryeithr5  stilhere5  cmokdcam5  othkdfos5  \
1        NaN        NaN        NaN        NaN        NaN        NaN   

   cmokddob5  othkdspn5  othkdrac21  okbornus5  okdisabl17  sexothkd6  \
1        NaN        NaN         NaN        NaN         NaN        NaN   

   relothkd6  adptotkd6  tryadopt6  tryeithr6  stilhere6  cmokdcam6  \
1        NaN        NaN        NaN        NaN        NaN        NaN   

   othkdfos6  cmokddob6  othkdspn6  othkdrac26  okbornus6  okdisabl21  \
1        NaN        NaN        NaN         NaN        NaN         NaN   

   sexothkd7  relothkd7  adptotkd7  tryadopt7  tryeithr7  stilhere7  \
1        NaN        NaN        NaN        NaN        NaN        NaN   

   cmokdcam7  othkdfos7  cmokddob7  othkdspn7  othkdrac31  okbornus7  \
1        NaN        NaN        NaN        NaN         NaN        NaN   

   okdisabl25  sexothkd8  relothkd8  adptotkd8  tryeithr8  stilhere8  \
1         NaN        NaN        NaN        NaN        NaN        NaN   

   cmokdcam8  othkdfos8  cmokddob8  othkdspn8  othkdrac36  othkdrac37  \
1        NaN        NaN        NaN        NaN         NaN         NaN   

   kdbstrac8  okbornus8  okdisabl29  sexothkd9  relothkd9  adptotkd9  \
1        NaN        NaN         NaN        NaN        NaN        NaN   

In [105]:
preg[preg['caseid']==5012]

caseid  pregordr  howpreg_n  howpreg_p  moscurrp  nowprgdk  pregend1  \
5515    5012         1        NaN        NaN       NaN       NaN       6.0   

      pregend2  nbrnaliv  multbrth  cmotpreg  prgoutcome  cmprgend  flgdkmo1  \
5515       NaN       1.0       NaN       NaN         1.0     991.0       NaN   

      cmprgbeg  ageatend  hpageend  gestasun_m  gestasun_w  wksgest  mosgest  \
5515     982.0       NaN       NaN         0.0        41.0     41.0      9.0   

      dk1gest  dk2gest  dk3gest  bpa_bdscheck1  bpa_bdscheck2  bpa_bdscheck3  \
5515      NaN      NaN      NaN            0.0            NaN            NaN   

      babysex  birthwgt_lb  birthwgt_oz  lobthwgt  babysex2  birthwgt_lb2  \
5515      2.0          6.0          0.0       NaN       NaN           NaN   

      birthwgt_oz2  lobthwgt2  babysex3  birthwgt_lb3  birthwgt_oz3  \
5515           NaN        NaN       NaN           NaN           NaN   

      lobthwgt3  cmbabdob  kidage  hpagelb  birthplc  paybirth1  paybirth2  \
5515        NaN     991.0   242.0     27.0       NaN        NaN        NaN   

      paybirth3  knewpreg  trimestr  ltrimest  priorsmk  postsmks  npostsmk  \
5515        NaN       NaN       NaN       NaN       NaN       NaN       NaN   

      getprena  bgnprena  pnctrim  lpnctri  workpreg  workborn  didwork  \
5515       NaN       NaN      NaN      NaN       NaN       NaN      NaN   

      matweeks  weeksdk  matleave  matchfound  livehere  alivenow  cmkidied  \
5515       NaN      NaN       NaN         NaN       NaN       NaN       NaN   

      cmkidlft  lastage  wherenow  legagree  parenend  anynurse  fedsolid  \
5515       NaN      NaN       NaN       NaN       NaN       NaN       NaN   

      frsteatd_n  frsteatd_p  frsteatd  quitnurs  ageqtnur_n  ageqtnur_p  \
5515         NaN         NaN       NaN       NaN         NaN         NaN   

      ageqtnur  matchfound2  livehere2  alivenow2  cmkidied2  cmkidlft2  \
5515       NaN          NaN        NaN        NaN        NaN        NaN   

      lastage2  wherenow2  legagree2  parenend2  anynurse2  fedsolid2  \
5515       NaN        NaN        NaN        NaN        NaN        NaN   

      frsteatd_n2  frsteatd_p2  frsteatd2  quitnurs2  ageqtnur_n2  \
5515          NaN          NaN        NaN        NaN          NaN   

      ageqtnur_p2  ageqtnur2  matchfound3  livehere3  alivenow3  cmkidied3  \
5515          NaN        NaN          NaN        NaN        NaN        NaN   

      cmkidlft3  lastage3  wherenow3  legagree3  parenend3  anynurse3  \
5515        NaN       NaN        NaN        NaN        NaN        NaN   

      fedsolid3  frsteatd_n3  frsteatd_p3  frsteatd3  quitnurs3  ageqtnur_n3  \
5515        NaN          NaN          NaN        NaN        NaN          NaN   

      ageqtnur_p3  ageqtnur3  cmlastlb  cmfstprg  cmlstprg  cmintstr  \
5515          NaN        NaN     991.0     991.0     991.0     958.0   

      cmintfin  cmintstrop  cmintfinop  cmintstrcr  cmintfincr  evuseint  \
5515     991.0       991.0      1233.0         NaN         NaN       1.0   

      stopduse  whystopd  whatmeth01  whatmeth02  whatmeth03  whatmeth04  \
5515       1.0       1.0         NaN         NaN         NaN         NaN   

      resnouse  wantbold  probbabe  cnfrmno  wantbld2  timingok  toosoon_n  \
5515       NaN       NaN       NaN      NaN       NaN       2.0        NaN   

      toosoon_p  wthpart1  wthpart2  feelinpg  hpwnold  timokhp  cohpbeg  \
5515        NaN       1.0       NaN       NaN        1      2.0      1.0   

      cohpend  tellfath  whentell  tryscale  wantscal  whyprg1  whyprg2  \
5515      1.0       NaN       NaN       NaN       NaN      NaN      NaN   

      whynouse1  whynouse2  whynouse3  anyusint  prglngth  outcome  birthord  \
5515        NaN        NaN        NaN         5        41        1       1.0   

      datend  agepreg  datecon  agecon  fmarout5  pmarpreg  rmarout6  \
5515   991.0    22.75      982    2200       1.0       2.0       1.0   

      fmarcon5

In [107]:
preg[preg['caseid']==5012].birthwgt_lb

5515    6.0
Name: birthwgt_lb, dtype: float64